#!/bin/sh

# Transmuter front-end, front-end libraries and utilities for the
# Transmuter language processing infrastructure
# Copyright (C) 2025  The Transmuter Project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e

die() {
    echo "$@"
    exit 2
}

invalid_type() {
    die Invalid modification type "'$1'".
}

invalid_subtype() {
    die Invalid modification subtype "'$2'" of type \'$1\'.
}

src_gen='common.py lexical.py syntactic.py'
src_hand='__init__.py __main__.py semantic.py back/__init__.py back/common.py back/python.py'

spec_1="$1"
shift
lib_1="$1"
shift
src_1="$1"
shift
spec_2="$1"
shift
lib_2="$1"
shift
src_2="$1"
shift

case "$1" in
    0)
        shift
        modify_spec=0
        modify_lib=0
        modify_src_gen=0
        modify_src_hand=1
        ;;
    1)
        shift
        modify_spec=0
        modify_lib=1
        modify_src_gen=0
        modify_src_hand=0
        ;;
    2)
        shift
        modify_spec=0
        modify_lib=1
        modify_src_gen=0
        modify_src_hand=1
        ;;
    3)
        shift
        modify_spec=0
        modify_lib=2
        modify_src_gen=0
        modify_src_hand=0
        ;;
    4)
        shift
        modify_spec=0
        modify_lib=2
        modify_src_gen=0
        modify_src_hand=1
        ;;
    5)
        shift
        modify_spec=0
        modify_lib=0

        case "$1" in
            1)
                shift
                modify_src_gen=0
                modify_src_hand=2
                ;;
            2)
                shift
                modify_src_gen=1
                modify_src_hand=0
                ;;
            *)
                invalid_subtype 5 "$1"
                ;;
        esac
        ;;
    6)
        shift
        modify_spec=0

        case "$1" in
            1)
                shift
                modify_lib=0
                modify_src_gen=0
                modify_src_hand=2
                ;;
            2)
                shift
                modify_lib=2
                modify_src_gen=2
                modify_src_hand=0
                ;;
            *)
                invalid_subtype 6 "$1"
                ;;
        esac
        ;;
    7)
        shift
        modify_spec=0

        case "$1" in
            1)
                shift
                modify_lib=0
                modify_src_gen=0
                modify_src_hand=2
                ;;
            2)
                shift
                modify_lib=2
                modify_src_gen=2
                modify_src_hand=1
                ;;
            *)
                invalid_subtype 7 "$1"
                ;;
        esac
        ;;
    8)
        shift
        modify_lib=0
        modify_src_hand=0

        case "$1" in
            1)
                shift
                modify_spec=1
                modify_src_gen=0
                ;;
            2)
                shift
                modify_spec=2
                modify_src_gen=2
                ;;
            *)
                invalid_subtype 8 "$1"
                ;;
        esac
        ;;
    9)
        shift
        modify_lib=0

        case "$1" in
            1)
                shift
                modify_spec=1
                modify_src_gen=0
                modify_src_hand=0
                ;;
            2)
                shift
                modify_spec=2
                modify_src_gen=2
                modify_src_hand=1
                ;;
            *)
                invalid_subtype 9 "$1"
                ;;
        esac
        ;;
    10)
        shift

        case "$1" in
            1)
                shift
                modify_spec=1
                modify_lib=0
                modify_src_gen=0
                modify_src_hand=2
                ;;
            2)
                shift
                modify_spec=2
                modify_lib=2
                modify_src_gen=2
                modify_src_hand=0
                ;;
            *)
                invalid_subtype 10 "$1"
                ;;
        esac
        ;;
    11)
        shift

        case "$1" in
            1)
                shift
                modify_spec=1
                modify_lib=0
                modify_src_gen=0
                modify_src_hand=2
                ;;
            2)
                shift
                modify_spec=2
                modify_lib=2
                modify_src_gen=2
                modify_src_hand=1
                ;;
            *)
                invalid_subtype 11 "$1"
                ;;
        esac
        ;;
    *)
        invalid_type "$1"
        ;;
esac

if [ $modify_spec = 0 ] && [ "$spec_1" != "$spec_2" ]; then
    diff -q -r "$spec_1" "$spec_2"
fi

if [ $modify_lib = 0 ] && [ "$lib_1" != "$lib_2" ]; then
    diff -q -r -x *.pyc "$lib_1/transmuter/front" "$lib_2/transmuter/front"
fi

if [ $modify_src_gen = 0 ] && [ "$src_1" != "$src_2" ]; then
    for filename in $src_gen; do
        diff -q "$src_1/transmuter/front/aether/$filename" "$src_2/transmuter/front/aether/$filename"
    done
fi

if [ $modify_src_hand = 0 ] && [ "$src_1" != "$src_2" ]; then
    for filename in $src_hand; do
        diff -q "$src_1/transmuter/front/aether/$filename" "$src_2/transmuter/front/aether/$filename"
    done
fi

mkdir -p tmp/1
mkdir tmp/2
PYTHONPATH="$lib_1":"$src_1" python3 -m transmuter.front.aether -L python -o tmp/1 "$spec_1"
PYTHONPATH="$lib_2":"$src_2" python3 -m transmuter.front.aether -L python -o tmp/2 "$spec_2"

if [ $modify_spec = 0 ] && [ $modify_src_hand != 2 ]; then
    diff -q -r tmp/1 tmp/2
fi

rm -r tmp
